On Error Resume Next
Sub GetTitleDateByName(strName, ByRef strTitle, ByRef strDate)
On Error Resume Next
strName = Mid(strName, InStrRev(strName, "/") + 1)
Select case UCase(strName)
Case "BEIJING.CHINA.YOUTH.DAILY-JIANSHUO-NEWSREPORT.GIF"
	strTitle = "Report mentioning Jian Shuo on China Youth Daily"
Case "CHANGSHA-JIANSHUO-MYHAND.JPG"
	strTitle = "Jian Shuo's left hand"
	strDate = "2001-12"
Case "CHANGSHA-JIANSHUO-ON.FLIGHT.BESIDES.WINDOW.LOOKING.RIGHTWARD.JPG"
	strTitle = "Beside window of plane before leaving for Changsha"
	strDate = "2001-12"
Case "CHANGSHA-JIANSHUO-ONFLIGHT.LOOKINGDOWN.JPG"
	strTitle = "On flight from Shanghai to Changsha, smiling"
	strDate = "2001-12"
Case "CHANGSHA-JIANSHUO-ONFLIGHT.STARING.JPG"
	strTitle = "On flight from Shanghai to Changsha, staring at camera"
	strDate = "2001-12"
Case "CHANGSHA-JIANSHUO-WITH.CAMERA.JPG"
	strTitle = "Working at the Hua Tian Hotel in Changsha"
Case "SHANGHAI.MEILONG-FANFAN-BEFORE.LEAVING.TO.CHANGSHA.LARGE.JPG"
	strTitle = "Fan Fan standing on Meilong street"
Case "SHANGHAI.JIANZHAO.VISIT-ANNA-IN.YELLOW.COAT.AT.SHOPPING.MALL.JPG"
	strTitle = "Anna in yellow coat"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-ANNA-PLAYING.WHILE.OTHERS.SHOP.FOR.SHOES.JPG"
	strTitle = "Anna playing while others shopping for shoes"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-ANNA-PRESSING.NOSE.JPG"
	strTitle = "Anna pressing her nose. Fun!"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-ANNA-WET.HAIR-0112.JPG"
	strTitle = "Wet hair Anna in shopping mall"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-ANNA-WET.HAIR.LOOKING.JPG"
	strTitle = "Wet hair Anna looking strangely"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-ANNA.FANFAN-FANFAN.HOLDING.ANNA.JPG"
	strTitle = "Fanfan holding Anna"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-ANNA.JIANZHAO-IN.SHOPPING.MALL.JPG"
	strTitle = "Anna and Jian Zhao in Grant Gateway"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-JIANSHUO.ANNA-HOLDING.ANNA.BEFORE.SHOES.WINDOW.JPG"
	strTitle = "Holding Anna in yellow coat"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-JIANSHUO.ANNA.FANFAN-IN.FUAN.SHOPPING.CENTER.JPG"
	strTitle = "Anna playing with Fan Fan"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-JIANSHUO.ANNA.FANFAN-PLAYING.JPG"
	strTitle = "Playing with Anna and Fan Fan"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-JIANSHUO.ANNA.LINGCHEN.FANFAN-DISCUSSION.JPG"
	strTitle = "Discussing with Ling Chen and Fan Fan"
	strDate = "2001-12"
Case "SHANGHAI.JIANZHAO.VISIT-JIANZHAO.ANNA.JIANFENG-ON.SOFA.JPG"
	strTitle = "Anna drinking milk between Jian Zhao and Jian Feng"
	strDate = "2001-12"
Case "HONGQIAO-MOM.JIANSHUO.DAD.JPG"
	strTitle = "With Mom at Hong Qiao Airport before they fly to Canada"
Case "LUOYANG-XIUHONG.BEIBEI.JPG"
	strTitle = "Bei Bei learning to walk with his mom"
Case "SHANGHAI.PIZZAHUT-JIANFENG-WITH.FANFAN.JIANSHUO.JPG"
	strTitle = "Jian Feng sitting in Pizza Hut, Shanghai"
	strDate = "2001-12"
Case "TORONTO-ANNA-THINKING.JPG"
	strTitle = "Anna at City Hall in Toronto"
Case "TORONTO-JIANZHAO.JPG"
	strTitle = "Jian Zhao on grassland in Toronto"
Case "BEIJING.PALACE-FANFAN.JPG"
	strTitle = "Fan Fan in Forbiden City"
	strDate = "1998-10"
Case "BEIJING.TIANTAN-FANFAN.JPG"
	strTitle = "Fan Fan in Tian Tan, Beijing"
	strDate = "1998-10"
Case "HANGZHOU-FANFAN-MEI.FLOWER.JPG"
	strTitle = "Fan Fan with Mei flowers in Hangzhou"
Case "HONGQIAO-FANFAN.DAD.JPG"
	strTitle = "Fan Fan with Father at Hong Qiao Airport, Shanghai"
Case "HONGQIAO-FANFAN.MOM-CLOSING.EYES.JPG"
	strTitle = "Fan Fan and Mom closing eyes together"
Case "HONGQIAO-FANFAN.MOM.DAD.JIANSHUO.JPG"
	strTitle = "The family at Hong Qiao"
Case "HONGQIAO-FANFAN.MOM.DAD.JPG"
	strTitle = "Fan Fan with Father and Mother"
Case "SHANGHAI.MEILONG-FANFAN-BEFORE.LEAVING.TO.CHANGSHA.JPG"
	strTitle = "Fan Fan on Meilong street"
Case "SHANGHAI.PIZZAHUT-FANFAN.JIANSHUO-TWINS.JPG"
	strTitle = "Fan Fan and Jian Shuo in Pizza Hut during Jian Feng's visit"
	strDate = "2001-12"
Case "SHANGHAI.PUDONG-FANFAN-BEFORE.TALL.BUILDINGS.JPG"
	strTitle = "Fan Fan before tall buildings in Pu Dong"
Case "SHANGHAI.PUDONG-FANFAN-PLANTS.JPG"
	strTitle = "Fan Fan in Lu Jia Zui before green plant in Pu Dong"
Case "SHANGHAI.PUDONG-FANFAN-STATUT-V2.JPG"
	strTitle = "Fan Fan with brozen statues in Pu Dong"
Case "GUANGZHOU-ZHAOLE.TAO.LIPENG.JPG"
	strTitle = "Zhao Le, Tao and Li Peng in Kuai Le Gu in Guangzhao"
Case "JIUHUASHANG-XIEZHENGMAO.JPG"
	strTitle = "Xie Zheng Mao in Jiu Hua Shan"
Case "LINXIAN-GUORUIFENG.JPG"
	strTitle = "Guo Rui Feng in Lin Xian"
	strDate = "2001-3"
Case "LUOYANG-CHUXIANGFENG.CLASS.8-TRAIN.JPG"
	strTitle = "Chu Xiang Feng and others standing before the train one day in 1994"
Case "LUOYANG-CLASS-SPORTS.CHAMP.JPG"
	strTitle = "Photo after 926 got the championship of sports meeting"
Case "LUOYANG-FENGTAO.CHUXIANGFENG.JPG"
	strTitle = "Feng Tao and Chu Xiang Feng chatting in rain"
Case "LUOYANG-GIRLS-BASKETBALL.CHAMP.JPG"
	strTitle = "Girls of 926 won the basketball championship "
Case "LUOYANG-HUORUI-BASKETBALL.JPG"
	strTitle = "Hui Rui playing basket ball"
Case "LUOYANG-JIANSHUO-ON.TREE.JPG"
	strTitle = "Boys of 926 playing on a tree"
Case "LUOYANG-NIEXIANGFENG.CHUXIANGFENG.JPG"
	strTitle = "Xie Xiang Feng and Chu Xiang Feng smiling before the train in 1994."
Case "LUOYANG-WANGHUIRUI.XIANANHUA.JPG"
	strTitle = "Wang Hui Rui and Xiang Nan Hua in cubicle in Wang Cheng Park"
Case "LUOYANG-XIANGFENG.CLASS.8-RAILWAY.JPG"
	strTitle = "All the members, tired after playing the whole afternoon while the Entrance Examination for Universities is close"
Case "LUOYANG-ZHANGQINGXIAN.JPG"
	strTitle = "The BOSS, Zhang Qing Xian is climbing the mount during the only spring outing of the 3 years."
Case "LUOYANG-ZHAOTIANXIANG.ZHAOLEI.JPG"
	strTitle = "Zhao Tian Xiang and Zhao Lei sitting on a table. Piles and piles of book as background"
Case "LUOYANG.LONGMEN-14.PERSONS.JPG"
	strTitle = "14 members visited Long Men"
Case "LUOYANG.LONGMEN-ZHANGYU..WANGJIANSHUO.ETC.JPG"
	strTitle = "Zhang Yu, Guo Chen, Cai Jin, Wang Li, etc in Long Men"
Case "LUOYANG.LUOYIGAO-ALL.926-MILLITARY.TRAINING.JPG"
	strTitle = "During millitary training in 1995"
Case "LUOYANG.LUOYIGAO-ALL.MEMBERS-GRADUATION.PHOTO.JPG"
	strTitle = "Class 926 graduation picture"
Case "LUOYANG.LUOYIGAO-BOYS-SPORT.MEETING.JPG"
	strTitle = "Super sports meeting. Fun!"
Case "NEWZEALAND-ZHANGMINGXIA.JPG"
	strTitle = "Zhang Ming Xia in New Zealand"
Case "SHANGHAI-XIEZHENGMAO-LOOKING.JPG"
	strTitle = "Xie Zheng Mao at the Bund in Shanghai"
Case "SHANGHAI-ZHANGXIAOGONG.JPG"
	strTitle = "Zhang Xiao Gong at dorm in Shanghai"
Case "SHANGHAI-ZHANGZIHENG.PENGZHIMING.XIEZHENGMAO.JPG"
	strTitle = "Zhang Zi Heng, Peng Zhi Ming and Xie Zheng Mao in Shanghai"
Case "SHANGHAI.SJTU-WANGJIANSHUO.XIEZHENGMAO.ZHANGZIHENG.PENGZHIMING.JPG"
	strTitle = "Wang Jian Shuo, Xie Zheng Mao, Zhang Zi Heng and Peng Zhi Ming in Shanghai Jiao Tong University in Octomber 1996"
Case "WUHAN-WANGMINGCHANG-LOOKING.BACK.JPG"
	strTitle = "Wang Ming Chang in Wu Han 2"
Case "WUHAN-WANGMINGCHANG.JPG"
	strTitle = "Wang Ming Chang in Wu Han"
Case "926SECRETPEOPLE.JPG"
	strTitle = "Secret people in 926"
Case "BEIJING-JIANSHUO-PRESENTATION.AT.CHINA.LOGISTIC.FORUM.JPG"
	strTitle = "Presentation on the 4th China Logistic Forum"
Case "COMPASS.JPG"
	strTitle = "My compass"
Case "SHANGHAI.EQUITIAL-JIANSHUO-PRESENTATION.BIZTALK.SERVER.JPG"
	strTitle = "Presentation - talking"
Case "SHANGHAI.EQUITIAL-JIANSHUO-TALKING.JPG"
	strTitle = "Presentation - smiling"
Case "SINGAPORE-JIANSHUO-STANDARD.SMALL.JPG"
	strTitle = "Jian Shuo Wang standard photo"
	strDate = "2000-12"
Case "SHANGHAI.MEILONG.HOUSE-BALLOONLAMP.JPG"
	strTitle = "Balloon lamp in Meilong house"
	strDate = "2001-12"
Case "SHANGHAI.MEILONG.HOUSE-COMPUTER-IN.DARK.JPG"
	strTitle = "My computer in Meilong house"
	strDate = "2001-12"
Case "SHANGHAI.MEILONG.HOUSE-LAMP-IN.DARK.JPG"
	strTitle = "Lamp in dark in Meilong house"
	strDate = "2001-12"
Case "SHANGHAI.MEILONG.HOUSE-POTANDORANGEJUICE.JPG"
	strTitle = "Pot and orange juice in Meilong house"
	strDate = "2001-12"
Case "SHANGHAI.MEILONG.HOUSE-REDHEADEDPOT.JPG"
	strTitle = "Red head pot in Meilong house"
	strDate = "2001-12"
Case "SHANGHAI.METRO.TOWER-CUBICLE.JPG"
	strTitle = "Cubicle background"
	strDate = "2001-12"
Case "SHANGHAI.METRO.TOWER-JIANSHUO-BEFORE.LAPTOP.JPG"
	strTitle = "Working before laptop in office"
	strDate = "2001-12"
Case "SHANGHAI.METRO.TOWER-JIANSHUO-SEATTLE.SHIRT.JPG"
	strTitle = "Working wearing the Seattle shirt"
	strDate = "2001-12"
Case "SHANGHAI.METRO.TOWER-JIANSHUO-STANDING.IN.CUBICLE.NOT.CLEAR.JPG"
	strTitle = "Standing in my cubicle at night"
	strDate = "2001-12"
Case "SHANGHAI.METRO.TOWER-JIANSHUO-STARING.AT.CAMERA.FOR.ZONGRUI.JPG"
	strTitle = "In office, staring at camera before Zong Rui went to Japan again"
	strDate = "2001-12"
Case "SHANGHAI.METRO.TOWER-JIANSHUO-THINK.IN.CUBICLE.JPG"
	strTitle = "Thinking in my cubicle at night"
	strDate = "2001-12"
Case "SHANGHAI.METRO.TOWER-LOBBY-ELEVATOR.ENTRANCE.JPG"
	strTitle = "Lobby of Metro Tower"
	strDate = "2001-12"
Case "SHANGHAI.METRO.TOWER-OUT.SIDE.WINDOW-JIANGUO.HOTEL.JPG"
	strTitle = "View outside my window - Jian Guo Hotel"
Case "SHANGHAI.METRO.TOWER-OUT.SIDE.WINDOW.JPG"
	strTitle = "View outside my window - south"
Case "SHANGHAI.METRO.TOWER-OUT.SITE.WINDOW-XU.JIA.HUI.SQUARE.JPG"
	strTitle = "View outside my window - Xu Jia Hui Square"
Case "XIAMEN-JIANSHUO-GOLD.JPG"
	strTitle = "Among the first to become SEA Gold Member in Xiamen"
Case "HAINAN-JIANSHUO-EAST.MOUNT.JPG"
	strTitle = "On East Mount. between San Ya and Hai Kou in Hannan"
Case "HAINAN-JIANSHUO-SAN.YA.BAY.JPG"
	strTitle = "Before San Ya Bay on Mount Lu Hui Tou"
Case "HANGZHOU.ZHEDA-JIANSHUO-BEFORE.BUILDING.JPG"
	strTitle = "On campus of Zhe Jiang University"
Case "HANGZHOU.ZHEDA-JIANSHUO-ONGRASS.JPG"
	strTitle = "On grass of Zhe Jiang University"
Case "HAINAN-XIANRENZHANG.JPG"
	strTitle = "Xian Ren Zhang before our hotel in Hainan"
Case "SINGAPORE-TALL.BUILDINGS.JPG"
	strTitle = "Tall buildings in Singapore"
	strDate = "2000-12"
Case "PORTLAND.HOUSE-WANGYUE.JPG"
	strTitle = "Wang Yue posing before her house"
Case "SEATTLE-JIANSHENG.WANGYUE.WANGHONG.ZHANGYAN.JPG"
	strTitle = "Jian Sheng's family in Seattle"
	strDate = "2000-6"
Case "SEATTLE-JIANSHUO.JIANSHENG.YANZHANG.JPG"
	strTitle = "With brother and siste-in-law in Seattle"
	strDate = "2000-6"
Case "SEATTLE-WATER.FRONT-SCENE.JPG"
	strTitle = "Seattle water front"
	strDate = "2000-6"
Case "SEATTLE.HOUSE-JIANSHUO-ALONE.JPG"
	strTitle = "Before Jiansheng's friend's house in Seattle with sun shine"
	strDate = "2000-6"
Case "SEATTLE.HOUSE-JIANSHUO.JPG"
	strTitle = "Before Jiansheng's friend's house in Seattle darker"
	strDate = "2000-6"
Case "SEATTLE.RAINER-WANGYUE.WANGHONG.JPG"
	strTitle = "Wang Yue and Wang Hong on Mount. Rainier"
	strDate = "2000-6"
Case "MALAYSIA-JIANSHUO-BEFORE.TWINS.TOWER.JPG"
	strTitle = "Before Twins Buiding in Malaysia"
	strDate = "2000-12"
Case "MALAYSIA-JIANSHUO-IN.BUS.SMALLL.JPG"
	strTitle = "In colorful bus in Malaysia"
	strDate = "2000-12"
Case "MALAYSIA-JIANSHUO-ON.PLAIN.GROUND.JPG"
	strTitle = "Sitting on ground of Hero Memorial of Malaysia"
	strDate = "2000-12"
Case "MALAYSIA-JIANSHUO-ON.SQUARE.JPG"
	strTitle = "On square of court in Malaysia"
	strDate = "2000-12"
Case "MALAYSIA-JIANSHUO-ON.STAGE.JPG"
	strTitle = "On stage of Hotel in Malaysia"
	strDate = "2000-12"
Case "MALAYSIA-JIANSHUO-WITH.BUS.DRIVER.JPG"
	strTitle = "With the Indian bus driver in Malaysia"
	strDate = "2000-12"
Case "MALAYSIA-JIANSHUO-WITH.FLAG.BY.HERO.MEMORIAL.JPG"
	strTitle = "With national flag of Malaysia"
	strDate = "2000-12"
Case "SINGAPORE-JIANSHUO-BEFORE.FULLERTON.HOTEL.JPG"
	strTitle = "Before Fullerton Hotel in Singapore"
	strDate = "2000-12"
Case "SINGAPORE-JIANSHUO-HUA.BA.SHAN.JPG"
	strTitle = "On Mount. Hua Ba in Singapore"
	strDate = "2000-12"
Case "SINGAPORE-JIANSHUO-PSA.JPG"
	strTitle = "Standing in Port PSA in Singapore"
	strDate = "2000-12"
Case "SINGAPORE-JIANSHUO-UNDER.SINGAPORE.BRIDGE.JPG"
	strTitle = "Under the Sinapore Bridge"
	strDate = "2000-12"
Case "XIAMEN.GULANGYU-JIANSHUO.JPG"
	strTitle = "At Gu Long Island in Xia Men"
Case "SHANGHAI.EQUATARIAL.HOTEL-JIANSHUO-PRESENTATION.JPG"
	strTitle = "Presentation in Equatarial Hotel"
Case "BOWANGPO.JPG"
	strTitle = "Name card of Bo Wang Po"
Case "SHANGHAI-EVER.BRIGHT.EXHIBITION.AND.CONVENSION.CENTER.JPG"
	strTitle = "Shanghai Ever Bright Convension and Exibition Center"
Case "SHANGHAI-VANKE.WALTZ.GARDEN-BIRDS.EYE.JPG"
	strTitle = "Bird eye view of Vanke Waltz Garden"
Case "SHANGHAI-VANKE.WALTZ.GARDEN-LOGO.GIF"
	strTitle = "Vanke Waltz Garden Logo"
Case "SHANGHAI-VANKE.WALTZ.GARDEN.JPG"
	strTitle = "Vanke Waltz Garden view from opposite side of street"

End Select
End Sub
Function GetTitleByName(strName) 
   Dim strTitle, strDate 
   GetTitleDateByName strName, strTitle, strDate 
   GetTitleByName = strTitle 
End Function 

Function GetDateByName(strName) 
   Dim strTitle, strDate 
   GetTitleDateByName strName, strTitle, strDate 
   GetDateByName = strDate 
End Function 
